### ISSUE TITLE
Help compiling

### ISSUE THREAD

**Issue by fenixdoido** [soxrok2212/mdk3-master#1]
Kali Linux 2.0 Sana

root@kali:~# cd ~/Desktop/Scripts/mdk3-master
root@kali:~/Desktop/Scripts/mdk3-master# make clean
rm -f mdk3
make -C osdep clean
make[1]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep'
make -C radiotap clean
make[2]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep/radiotap'
rm -f *.o
make[2]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep/radiotap'
rm -f libosdep.a  *.o .os.*
make[1]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep'
root@kali:~/Desktop/Scripts/mdk3-master# make clean
rm -f mdk3
make -C osdep clean
make[1]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep'
make -C radiotap clean
make[2]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep/radiotap'
rm -f *.o
make[2]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep/radiotap'
rm -f libosdep.a  *.o .os.*
make[1]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep'
root@kali:~/Desktop/Scripts/mdk3-master# make clean
rm -f mdk3
make -C osdep clean
make[1]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep'
make -C radiotap clean
make[2]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep/radiotap'
rm -f *.o
make[2]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep/radiotap'
rm -f libosdep.a  *.o .os.*
make[1]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep'
root@kali:~/Desktop/Scripts/mdk3-master# make clean
rm -f mdk3
make -C osdep clean
make[1]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep'
make -C radiotap clean
make[2]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep/radiotap'
rm -f *.o
make[2]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep/radiotap'
rm -f libosdep.a  *.o .os.*
make[1]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep'
root@kali:~/Desktop/Scripts/mdk3-master# clear
[3;J
root@kali:~/Desktop/Scripts/mdk3-master# make
make -C osdep
make[1]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep'
Building for Linux
make[2]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep'
gcc -g -W -Wall -Wextra -O3 -Wno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk3-v6  -fPIC -I..    -c -o osdep.o osdep.c
gcc -g -W -Wall -Wextra -O3 -Wno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk3-v6  -fPIC -I..    -c -o common.o common.c
gcc -g -W -Wall -Wextra -O3 -Wno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk3-v6  -fPIC -I..    -c -o network.o network.c
gcc -g -W -Wall -Wextra -O3 -Wno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk3-v6  -fPIC -I..    -c -o linux.o linux.c
linux.c: In function ‘is_ndiswrapper’:
linux.c:165:17: warning: variable ‘unused’ set but not used [-Wunused-but-set-variable]
     int n, pid, unused;
                 ^
linux.c: In function ‘linux_set_rate’:
linux.c:334:22: warning: variable ‘unused’ set but not used [-Wunused-but-set-variable]
     int pid, status, unused;
                      ^
linux.c: In function ‘linux_read’:
linux.c:498:27: warning: argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
     memset( buf, 0, sizeof( buf ) );
                           ^
linux.c: In function ‘linux_set_channel’:
linux.c:807:22: warning: variable ‘unused’ set but not used [-Wunused-but-set-variable]
     int pid, status, unused;
                      ^
linux.c: In function ‘linux_set_freq’:
linux.c:896:22: warning: variable ‘unused’ set but not used [-Wunused-but-set-variable]
     int pid, status, unused;
                      ^
linux.c: In function ‘set_monitor’:
linux.c:1022:22: warning: variable ‘unused’ set but not used [-Wunused-but-set-variable]
     int pid, status, unused;
                      ^
linux.c: In function ‘do_linux_open’:
linux.c:1366:12: warning: variable ‘unused_str’ set but not used [-Wunused-but-set-variable]
     char * unused_str;
            ^
linux.c:1352:15: warning: variable ‘unused’ set but not used [-Wunused-but-set-variable]
     int kver, unused;
               ^
linux.c: In function ‘get_battery_state’:
linux.c:1982:35: warning: variable ‘current’ set but not used [-Wunused-but-set-variable]
         int rate = 1, remain = 0, current = 0;
                                   ^
gcc -g -W -Wall -Wextra -O3 -Wno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk3-v6  -fPIC -I..    -c -o linux_tap.o linux_tap.c
gcc -g -W -Wall -Wextra -O3 -Wno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk3-v6  -fPIC -I..    -c -o radiotap/radiotap-parser.o radiotap/radiotap-parser.c
ar cru libosdep.a  osdep.o common.o network.o linux.o linux_tap.o radiotap/radiotap-parser.o common.o
ranlib libosdep.a 
touch .os.Linux
make[2]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep'
make[1]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep'
cc -g -O3 -w mdk3.c osdep/libosdep.a -o mdk3 -Losdep -losdep -lpthread
root@kali:~/Desktop/Scripts/mdk3-master# make install
make -C osdep install
make[1]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep'
Building for Linux
make[2]: Entering directory '/root/Desktop/Scripts/mdk3-master/osdep'
make[2]: '.os.Linux' is up to date.
make[2]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep'
make[1]: Leaving directory '/root/Desktop/Scripts/mdk3-master/osdep'
install -D -m 0755 mdk3 //usr/local/sbin/mdk3
root@kali:~/Desktop/Scripts/mdk3-master#

**Comment by crushedice2000** [comment]
Where is the error?

Also, please note that adding 4 spaces before each line styles the code block.
